// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A CloudRepoSourceContext denotes a particular revision in a cloud
/// repo (a repo hosted by the Google Cloud Platform).
public struct CloudRepoSourceContext: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The ID of the repo.
  public var repoId: RepoId? = nil

  /// A revision in a cloud repository can be identified by either its revision
  /// ID or its Alias.
  public var revision: RevisionOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CloudRepoSourceContext`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudRepoSourceContext().with { $0.repoId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let repoId = CodingKeys(stringValue: "repoId")
    static let revisionId = CodingKeys(stringValue: "revisionId")
    static let aliasName = CodingKeys(stringValue: "aliasName")
    static let aliasContext = CodingKeys(stringValue: "aliasContext")

    static let _knownKeys: Set<Swift.String> = [
      "repoId",
      "revisionId",
      "aliasName",
      "aliasContext",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.repoId = try container.decodeIfPresent(RepoId.self, forKey: .repoId)

    var revision: RevisionOneOf? = nil
    let revisionCheckAndSet = {
      if revision != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'revision'"))
      }
      revision = $0
    }
    if let revisionId = try container.decodeIfPresent(Swift.String.self, forKey: .revisionId) {
      try revisionCheckAndSet(.revisionId(revisionId))
    }
    if let aliasName = try container.decodeIfPresent(Swift.String.self, forKey: .aliasName) {
      try revisionCheckAndSet(.aliasName(aliasName))
    }
    if let aliasContext = try container.decodeIfPresent(AliasContext.self, forKey: .aliasContext) {
      try revisionCheckAndSet(.aliasContext(aliasContext))
    }
    self.revision = revision
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.repoId, forKey: .repoId)

    if let choice = self.revision {
      switch choice {
      case .revisionId(let value):
        try container.encode(value, forKey: .revisionId)
      case .aliasName(let value):
        try container.encode(value, forKey: .aliasName)
      case .aliasContext(let value):
        try container.encode(value, forKey: .aliasContext)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A revision in a cloud repository can be identified by either its revision
  /// ID or its Alias.
  public enum RevisionOneOf: Codable, Equatable, Sendable {
    /// A revision ID.
    case revisionId(Swift.String)
    /// The name of an alias (branch, tag, etc.).
    @available(*, deprecated)
    case aliasName(Swift.String)
    /// An alias, which may be a branch or tag.
    indirect case aliasContext(AliasContext)
  }

  /// The type URL for `CloudRepoSourceContext`: `"type.googleapis.com/google.devtools.source.v1.CloudRepoSourceContext"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.source.v1.CloudRepoSourceContext"
  }

  /// Initialize an instance of `CloudRepoSourceContext` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.devtools.source.v1.CloudRepoSourceContext"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `CloudRepoSourceContext` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
